version: '3.8'

services:
  backend:
    build: .
    ports:
      - '5000:5000'
      - '5555:5555'
    env_file:
      - .env
    depends_on:
      - postgres
    # restart: always
    restart: 'no'
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - '5432:5432'
    # restart: always
    restart: 'no'
    environment:
      POSTGRES_USER: rahat
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kobe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
